runtime: nodejs14
service: back
beta_settings:
  cloud_sql_instances: pe-pacasmayo-portalmat-gcp-prd:us-central1:portalmat-db-prd
env_variables:
  NODE_ENV: production
  KEY_SEND_GRID: string
  SQL_USER: portalmat_prd
  SQL_PASSWORD: P@cA$maY0.+22
  SQL_DATABASE: portalmat-db-prd
  SQL_PORT: 5432
  INSTANCE_CONNECTION_NAME: pe-pacasmayo-portalmat-gcp-prd:us-central1:portalmat-db-prd
  DB_SOCKET_PATH : /cloudsql
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50